name: test
on: [push, pull_request]
jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Run calendar pre-commit audit
        run: bash pre_commit_audit.sh
      - name: Setup Flutter for mobile
        working-directory: mobile
      - run: flutter pub get
        working-directory: mobile
      - run: flutter test test/kemetic_calendar_golden_test.dart
        working-directory: mobile
