import {
  Archive,
  BarChart3,
  BookOpen,
  Bot,
  ClipboardCheck,
  Copy,
  FileSearch,
  FlaskConical,
  Gauge,
  HeartPulse,
  Landmark,
  LayoutDashboard,
  Library,
  LockKeyhole,
  MessageSquareText,
  Network,
  ScrollText,
  Settings,
  Shield,
  Sparkles,
  Users,
  WalletCards,
} from "lucide-react";

export type AdminRoute = {
  path: string;
  label: string;
  group: "Product" | "War Room" | "Ops" | "Infrastructure" | "Settings";
  purpose: string;
  phase: string;
  state: "active" | "phase1" | "locked";
  Icon: typeof LayoutDashboard;
};

export const adminRoutes: AdminRoute[] = [
  {
    group: "Product",
    path: "/product/overview",
    label: "Overview",
    purpose: "A starting point for product operations and rollout status.",
    phase: "Phase 1",
    state: "phase1",
    Icon: LayoutDashboard,
  },
  {
    group: "Product",
    path: "/product/users",
    label: "Users",
    purpose: "Support-safe user summaries and account health will live here.",
    phase: "Phase 2",
    state: "locked",
    Icon: Users,
  },
  {
    group: "Product",
    path: "/product/maat",
    label: "Ma'at",
    purpose: "Read-only Ma'at operations, dry-runs, and controlled policy drafts.",
    phase: "Phase 6",
    state: "active",
    Icon: HeartPulse,
  },
  {
    group: "Product",
    path: "/product/content-lab",
    label: "Content Lab",
    purpose:
      "Generate user-specific previews, inspect evidence, and store operator critiques.",
    phase: "Phase 7",
    state: "active",
    Icon: FlaskConical,
  },
  {
    group: "Product",
    path: "/product/nodes",
    label: "Nodes",
    purpose: "Draft-only node CMS that follows ADR-002 source-of-truth limits.",
    phase: "Phase 6",
    state: "active",
    Icon: Network,
  },
  {
    group: "War Room",
    path: "/war-room/dashboard",
    label: "Dashboard",
    purpose: "A read-only dashboard for app health and Ma'at outcomes.",
    phase: "Phase 2",
    state: "active",
    Icon: Gauge,
  },
  {
    group: "War Room",
    path: "/war-room/reports",
    label: "Reports",
    purpose: "Weekly operating reports and generated summaries will appear here.",
    phase: "Phase 5",
    state: "active",
    Icon: ScrollText,
  },
  {
    group: "War Room",
    path: "/war-room/metrics",
    label: "Metrics",
    purpose: "Focused metric tables and drilldowns without raw private content.",
    phase: "Phase 2",
    state: "active",
    Icon: BarChart3,
  },
  {
    group: "Ops",
    path: "/ops/research",
    label: "Research",
    purpose: "Research briefs with citations will be generated into Archive.",
    phase: "Phase 3 echo",
    state: "active",
    Icon: FileSearch,
  },
  {
    group: "Ops",
    path: "/ops/social",
    label: "Social",
    purpose: "Manual-post social drafts will be generated here.",
    phase: "Phase 3 echo",
    state: "active",
    Icon: MessageSquareText,
  },
  {
    group: "Ops",
    path: "/ops/copy",
    label: "Copy",
    purpose: "Copy variants for app, store, support, and landing surfaces.",
    phase: "Phase 3 echo",
    state: "active",
    Icon: Copy,
  },
  {
    group: "Ops",
    path: "/ops/suggest-updates",
    label: "Suggest Updates",
    purpose: "War Room-backed product and content suggestions.",
    phase: "Phase 3 echo",
    state: "active",
    Icon: Sparkles,
  },
  {
    group: "Ops",
    path: "/ops/product-qa",
    label: "Product QA",
    purpose: "Codex-ready specs from bugs, observations, and feature ideas.",
    phase: "Phase 3 echo",
    state: "active",
    Icon: ClipboardCheck,
  },
  {
    group: "Ops",
    path: "/ops/chief-operator",
    label: "Chief Operator",
    purpose: "The weekly operating brief and top actions.",
    phase: "Phase 3 echo",
    state: "active",
    Icon: Bot,
  },
  {
    group: "Infrastructure",
    path: "/infrastructure/archive",
    label: "Archive",
    purpose: "Research, copy, social, decisions, and lessons will be stored here.",
    phase: "Phase 3",
    state: "active",
    Icon: Archive,
  },
  {
    group: "Infrastructure",
    path: "/infrastructure/armory",
    label: "Armory",
    purpose: "Reusable playbooks and rules for future ops agents.",
    phase: "Phase 3",
    state: "active",
    Icon: BookOpen,
  },
  {
    group: "Infrastructure",
    path: "/infrastructure/approvals",
    label: "Approvals",
    purpose: "The central approval inbox for gated decisions.",
    phase: "Phase 3",
    state: "active",
    Icon: ClipboardCheck,
  },
  {
    group: "Infrastructure",
    path: "/infrastructure/treasury",
    label: "Treasury",
    purpose: "Lightweight cost and budget tracking for agent runs.",
    phase: "Phase 3",
    state: "active",
    Icon: Landmark,
  },
  {
    group: "Infrastructure",
    path: "/infrastructure/media-bay",
    label: "Media Bay",
    purpose: "Optional social assets and campaign media support.",
    phase: "Phase 5 optional",
    state: "locked",
    Icon: Library,
  },
  {
    group: "Settings",
    path: "/settings/staff",
    label: "Staff",
    purpose: "Staff membership management after the first owner is bootstrapped.",
    phase: "Phase 3",
    state: "locked",
    Icon: Shield,
  },
  {
    group: "Settings",
    path: "/settings/security",
    label: "Security",
    purpose: "Security posture, session policy, and break-glass rules.",
    phase: "Phase 1",
    state: "phase1",
    Icon: LockKeyhole,
  },
  {
    group: "Settings",
    path: "/settings/system",
    label: "System",
    purpose: "Deployment and function status checks will be gathered here.",
    phase: "Phase 2",
    state: "locked",
    Icon: Settings,
  },
  {
    group: "Settings",
    path: "/settings/billing",
    label: "Billing",
    purpose: "Budget signals are represented in Treasury, not a full finance system.",
    phase: "Not active",
    state: "locked",
    Icon: WalletCards,
  },
];

export const allAdminRoutes = adminRoutes;

export const routeGroups = [
  "Product",
  "War Room",
  "Ops",
  "Infrastructure",
  "Settings",
] as const;
