-- Phase 1: completion store keyed by client_event_id + completed_on (survives reschedule)
-- RLS + unique + index for RPC; trigger validates at insert only.

create table if not exists public.user_event_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_event_id text not null,
  flow_id bigint not null references public.flows(id) on delete cascade,
  completed_on date not null,
  completed_at timestamptz not null default now(),
  source text not null default 'client',
  metadata jsonb
);

create unique index if not exists user_event_completions_user_client_event_uniq
  on public.user_event_completions (user_id, client_event_id);

create index if not exists user_event_completions_flow_completed_on_idx
  on public.user_event_completions (flow_id, completed_on);

alter table public.user_event_completions enable row level security;

drop policy if exists user_event_completions_select_own on public.user_event_completions;
create policy user_event_completions_select_own on public.user_event_completions
  for select using (user_id = auth.uid());

drop policy if exists user_event_completions_insert_own on public.user_event_completions;
create policy user_event_completions_insert_own on public.user_event_completions
  for insert with check (user_id = auth.uid());

drop policy if exists user_event_completions_update_own on public.user_event_completions;
create policy user_event_completions_update_own on public.user_event_completions
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists user_event_completions_delete_own on public.user_event_completions;
create policy user_event_completions_delete_own on public.user_event_completions
  for delete using (user_id = auth.uid());

-- Validate at insert: event must exist for this user and flow (prevents spoofing).
-- After reschedule the event row may be deleted; we do NOT re-validate on update so existing completions stay.
create or replace function public.user_event_completions_validate_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.user_events ue
    where ue.user_id = new.user_id
      and ue.client_event_id = new.client_event_id
      and ue.flow_local_id = new.flow_id
  ) then
    raise exception 'user_event_completions: no user_events row for (user_id, client_event_id, flow_id)';
  end if;
  return new;
end;
$$;

drop trigger if exists user_event_completions_validate_before_insert on public.user_event_completions;
create trigger user_event_completions_validate_before_insert
  before insert on public.user_event_completions
  for each row execute function public.user_event_completions_validate_insert();

-- Optional RPC for clients: validates and upserts one completion.
create or replace function public.record_event_completion(
  p_client_event_id text,
  p_flow_id bigint,
  p_completed_on date,
  p_source text default 'client'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'not authenticated'; end if;
  if p_client_event_id is null or p_client_event_id = '' then raise exception 'client_event_id required'; end if;
  if p_flow_id is null then raise exception 'flow_id required'; end if;
  if p_completed_on is null then raise exception 'completed_on required'; end if;

  if not exists (
    select 1 from public.user_events ue
    where ue.user_id = v_uid
      and ue.client_event_id = p_client_event_id
      and ue.flow_local_id = p_flow_id
  ) then
    raise exception 'event not found or not owned';
  end if;

  insert into public.user_event_completions (user_id, client_event_id, flow_id, completed_on, completed_at, source)
  values (v_uid, p_client_event_id, p_flow_id, p_completed_on, now(), coalesce(p_source, 'client'))
  on conflict (user_id, client_event_id) do update set
    completed_on = excluded.completed_on,
    completed_at = excluded.completed_at,
    source = excluded.source;
end;
$$;

comment on table public.user_event_completions is
'Phase 1: one row per completed event; keyed by client_event_id so completions survive reschedule. completed_on = flow-window date; completed_at = audit timestamp.';

comment on function public.record_event_completion(text, bigint, date, text) is
'Validates ownership and upserts a completion keyed by client_event_id + completed_on; use instead of direct insert if preferred.';

revoke all on function public.record_event_completion(text, bigint, date, text) from public;
grant execute on function public.record_event_completion(text, bigint, date, text) to authenticated;
