-- ============================================================================
-- Flow lineage, user-safe cache, generation handshake, outcomes & saves
-- ============================================================================

-- 1) flow_generation_logs: add generation_id + versions
alter table public.flow_generation_logs
  add column if not exists generation_id uuid,
  add column if not exists schema_version text,
  add column if not exists policy_version text;

create index if not exists flow_generation_logs_generation_id_idx
  on public.flow_generation_logs (generation_id)
  where generation_id is not null;

create unique index if not exists flow_generation_logs_generation_id_uniq
  on public.flow_generation_logs (generation_id)
  where generation_id is not null;

-- 2) flows: add origin/lineage columns
alter table public.flows
  add column if not exists origin_type text,
  add column if not exists origin_flow_id bigint,
  add column if not exists origin_share_id uuid,
  add column if not exists origin_generation_id uuid,
  add column if not exists root_flow_id bigint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'flows_origin_type_check') then
    alter table public.flows
      add constraint flows_origin_type_check
      check (origin_type is null or origin_type in ('manual','ai','share_import','profile_import','fork','template'));
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'flows_origin_flow_id_fkey') then
    alter table public.flows add constraint flows_origin_flow_id_fkey foreign key (origin_flow_id) references public.flows(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'flows_root_flow_id_fkey') then
    alter table public.flows add constraint flows_root_flow_id_fkey foreign key (root_flow_id) references public.flows(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'flows_origin_share_id_fkey') then
    alter table public.flows add constraint flows_origin_share_id_fkey foreign key (origin_share_id) references public.flow_shares(id) on delete set null;
  end if;
end $$;

create index if not exists flows_origin_flow_id_idx on public.flows(origin_flow_id);
create index if not exists flows_origin_share_id_idx on public.flows(origin_share_id);
create index if not exists flows_origin_generation_id_idx on public.flows(origin_generation_id);
create index if not exists flows_root_flow_id_idx on public.flows(root_flow_id);

-- 3) flow_generation_cache: add version columns + user-safe key index
alter table public.flow_generation_cache
  add column if not exists snapshot_version text,
  add column if not exists schema_version text,
  add column if not exists policy_version text;

create unique index if not exists flow_generation_cache_key_uniq
  on public.flow_generation_cache (user_id, coalesce(snapshot_version, ''), coalesce(schema_version, ''), coalesce(policy_version, ''), input_hash)
  where user_id is not null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'flow_generation_cache_user_versions_hash_key') then
    alter table public.flow_generation_cache
      add constraint flow_generation_cache_user_versions_hash_key
      unique (user_id, snapshot_version, schema_version, policy_version, input_hash);
  end if;
end $$;

create index if not exists flow_generation_cache_lookup_idx
  on public.flow_generation_cache (user_id, coalesce(snapshot_version, ''), coalesce(schema_version, ''), coalesce(policy_version, ''), input_hash, created_at desc)
  where user_id is not null;

-- 4) flow_outcomes
create table if not exists public.flow_outcomes (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  flow_id bigint not null,
  window_start date,
  window_end date,
  events_total integer,
  events_completed integer,
  edit_count integer,
  accepted_as_is boolean,
  feedback_tags text[],
  user_rating smallint,
  recorded_at timestamptz not null default now(),
  metadata jsonb
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.flow_outcomes'::regclass
      and conname  = 'flow_outcomes_user_id_fkey'
  ) then
    alter table public.flow_outcomes
      add constraint flow_outcomes_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.flow_outcomes'::regclass
      and conname  = 'flow_outcomes_flow_id_fkey'
  ) then
    alter table public.flow_outcomes
      add constraint flow_outcomes_flow_id_fkey
      foreign key (flow_id) references public.flows(id) on delete cascade;
  end if;
end $$;

create unique index if not exists flow_outcomes_one_per_window_uniq on public.flow_outcomes (user_id, flow_id, window_start) where window_start is not null;
create index if not exists flow_outcomes_user_id_idx on public.flow_outcomes(user_id);
create index if not exists flow_outcomes_flow_id_idx on public.flow_outcomes(flow_id);
create index if not exists flow_outcomes_recorded_at_idx on public.flow_outcomes(recorded_at desc);

alter table public.flow_outcomes enable row level security;
drop policy if exists flow_outcomes_select_own on public.flow_outcomes;
create policy flow_outcomes_select_own on public.flow_outcomes for select using (user_id = auth.uid());

drop policy if exists flow_outcomes_insert_own on public.flow_outcomes;
create policy flow_outcomes_insert_own on public.flow_outcomes for insert with check (user_id = auth.uid());

drop policy if exists flow_outcomes_update_own on public.flow_outcomes;
create policy flow_outcomes_update_own on public.flow_outcomes for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists flow_outcomes_delete_own on public.flow_outcomes;
create policy flow_outcomes_delete_own on public.flow_outcomes for delete using (user_id = auth.uid());

-- 5) flow_saves
create table if not exists public.flow_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  flow_id bigint not null,
  saved_from text not null,
  saved_at timestamptz not null default now(),
  metadata jsonb
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.flow_saves'::regclass
      and conname  = 'flow_saves_saved_from_check'
  ) then
    alter table public.flow_saves
      add constraint flow_saves_saved_from_check
      check (saved_from in ('profile','share','inbox','search','ai','self'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.flow_saves'::regclass
      and conname  = 'flow_saves_user_id_fkey'
  ) then
    alter table public.flow_saves
      add constraint flow_saves_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.flow_saves'::regclass
      and conname  = 'flow_saves_flow_id_fkey'
  ) then
    alter table public.flow_saves
      add constraint flow_saves_flow_id_fkey
      foreign key (flow_id) references public.flows(id) on delete cascade;
  end if;
end $$;

create unique index if not exists flow_saves_user_flow_uniq on public.flow_saves (user_id, flow_id);
create index if not exists flow_saves_user_id_idx on public.flow_saves(user_id);
create index if not exists flow_saves_flow_id_idx on public.flow_saves(flow_id);
create index if not exists flow_saves_saved_at_idx on public.flow_saves(saved_at desc);

alter table public.flow_saves enable row level security;
drop policy if exists flow_saves_select_own on public.flow_saves;
create policy flow_saves_select_own on public.flow_saves for select using (user_id = auth.uid());

drop policy if exists flow_saves_insert_own on public.flow_saves;
create policy flow_saves_insert_own on public.flow_saves for insert with check (user_id = auth.uid());

drop policy if exists flow_saves_update_own on public.flow_saves;
create policy flow_saves_update_own on public.flow_saves for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists flow_saves_delete_own on public.flow_saves;
create policy flow_saves_delete_own on public.flow_saves for delete using (user_id = auth.uid());

-- 6) flow_commit RPC
create or replace function public.flow_commit(p_generation_id uuid, p_flow_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if p_generation_id is null then raise exception 'generation_id is required'; end if;
  if p_flow_id is null then raise exception 'flow_id is required'; end if;
  if not exists (select 1 from public.flows f where f.id = p_flow_id and f.user_id = auth.uid()) then
    raise exception 'Not authorized to commit for this flow';
  end if;
  if not exists (select 1 from public.flow_generation_logs l where l.generation_id = p_generation_id and l.user_id = auth.uid()) then
    raise exception 'Not authorized to commit for this generation_id';
  end if;
  update public.flow_generation_logs set flow_id = p_flow_id where generation_id = p_generation_id and user_id = auth.uid();
  update public.flows set origin_generation_id = p_generation_id, origin_type = coalesce(origin_type, 'ai') where id = p_flow_id and user_id = auth.uid();
end;
$$;

revoke all on function public.flow_commit(uuid, bigint) from public;
grant execute on function public.flow_commit(uuid, bigint) to authenticated;
