-- Seed the full canonical node list used by the mobile node library.
-- This unblocks insight saves, which resolve a node slug to public.nodes.id.

insert into public.nodes (slug, title, glyph, body_text, aliases, node_type, sort_key)
values
('serpent', 'Serpent', '𓆑', 'Canonical Kemetic node: Serpent.', '["Apophis", "Mehen"]'::jsonb, 'animal', 1),
('hawk', 'Hawk (Heru)', '𓅃', 'Canonical Kemetic node: Hawk (Heru).', '["Eye of Horus", "Eye of Heru"]'::jsonb, 'animal', 2),
('jackal', 'Jackal (Anpu)', '𓃢', 'Canonical Kemetic node: Jackal (Anpu).', '["Anubis", "Anpu"]'::jsonb, 'animal', 3),
('nile', 'Nile (Hapy)', '𓇋𓏏𓊖', 'Canonical Kemetic node: Nile (Hapy).', '["Hapy", "Nile"]'::jsonb, 'earth', 4),
('ptah', 'Ptah', '𓊪𓏏𓎛', 'Canonical Kemetic node: Ptah.', '[]'::jsonb, 'builder', 5),
('djehuty', 'Djehuty', '𓅝', 'Canonical Kemetic node: Djehuty.', '["Thoth", "Djehuty"]'::jsonb, 'netjer', 6),
('shu', 'Shu', '𓇳𓏏', 'Canonical Kemetic node: Shu.', '[]'::jsonb, 'netjer', 7),
('maat', 'Ma’at', '𓆄', 'Canonical Kemetic node: Ma’at.', '[]'::jsonb, 'metaphysical', 8),
('ausar', 'Ausar', '𓁹', 'Canonical Kemetic node: Ausar.', '["Osiris", "Ausar", "Asar"]'::jsonb, 'netjer', 9),
('aset', 'Aset', '𓊨', 'Canonical Kemetic node: Aset.', '["Isis", "Aset"]'::jsonb, 'netjer', 10),
('heru', 'Heru', '𓅃', 'Canonical Kemetic node: Heru.', '["Horus", "Heru"]'::jsonb, 'netjer', 11),
('isfet', 'Isfet', '𓊹', 'Canonical Kemetic node: Isfet.', '[]'::jsonb, 'metaphysical', 12),
('ra', 'Ra', '𓇳', 'Canonical Kemetic node: Ra.', '[]'::jsonb, 'cosmic', 13),
('ka', 'Ka', '𓂓', 'Canonical Kemetic node: Ka.', '[]'::jsonb, 'metaphysical', 14),
('ba', 'Ba', '𓅽', 'Canonical Kemetic node: Ba.', '[]'::jsonb, 'metaphysical', 15),
('akh', 'Akh', '𓅜', 'Canonical Kemetic node: Akh.', '[]'::jsonb, 'metaphysical', 16),
('ren', 'Ren (Name)', '𓂋𓈖', 'Canonical Kemetic node: Ren (Name).', '[]'::jsonb, 'metaphysical', 17),
('ib', 'Ib (Heart)', '𓄣', 'Canonical Kemetic node: Ib (Heart).', '[]'::jsonb, 'metaphysical', 18),
('sheut', 'Sheut (Shadow)', '𓈐', 'Canonical Kemetic node: Sheut (Shadow).', '[]'::jsonb, 'metaphysical', 19),
('imhotep', 'Imhotep', '𓇋𓐍𓅓𓏏𓊪', 'Canonical Kemetic node: Imhotep.', '["Imhotep"]'::jsonb, 'builder', 20),
('sopdet', 'Sopdet (Sirius)', '𓇼', 'Canonical Kemetic node: Sopdet (Sirius).', '["Sopdet", "Sothis", "Sirius"]'::jsonb, 'cosmic', 21),
('coffin_texts', 'Coffin Texts', '𓏏', 'Canonical Kemetic node: Coffin Texts.', '[]'::jsonb, 'metaphysical', 22),
('papyrus_chester_beatty_iv', 'Papyrus Chester Beatty IV', '𓏞', 'Canonical Kemetic node: Papyrus Chester Beatty IV.', '[]'::jsonb, 'metaphysical', 23),
('kemet', 'Kemet (Black Land)', '𓈎', 'Canonical Kemetic node: Kemet (Black Land).', '[]'::jsonb, 'earth', 24),
('pyramid_texts', 'Pyramid Texts', '𓉐', 'Canonical Kemetic node: Pyramid Texts.', '[]'::jsonb, 'metaphysical', 25),
('hathor', 'Hathor', '𓇋𓏏𓆑', 'Canonical Kemetic node: Hathor.', '["Hathor"]'::jsonb, 'netjer', 26),
('dendera', 'Dendera', '𓉗', 'Canonical Kemetic node: Dendera.', '[]'::jsonb, 'earth', 27),
('sah', 'Sah (Orion)', '✷', 'Canonical Kemetic node: Sah (Orion).', '[]'::jsonb, 'cosmic', 28),
('abydos', 'Abydos', '𓉐', 'Canonical Kemetic node: Abydos.', '[]'::jsonb, 'earth', 29),
('decans', 'Decans', '✵', 'Canonical Kemetic node: Decans.', '[]'::jsonb, 'cosmic', 30),
('duat', 'Duat', '𓁢', 'Canonical Kemetic node: Duat.', '["Duat"]'::jsonb, 'cosmic', 31),
('renenutet', 'Renenutet', '𓆤', 'Canonical Kemetic node: Renenutet.', '[]'::jsonb, 'netjer', 32),
('house_of_life', 'House of Life (Per Ankh)', '𓏠', 'Canonical Kemetic node: House of Life (Per Ankh).', '[]'::jsonb, 'builder', 33),
('instruction_ptahhotep', 'Instruction of Ptahhotep', '𓏏', 'Canonical Kemetic node: Instruction of Ptahhotep.', '[]'::jsonb, 'metaphysical', 34),
('sekhmet', 'Sekhmet', '𓃭', 'Canonical Kemetic node: Sekhmet.', '[]'::jsonb, 'netjer', 35),
('rekh_wer', 'Rekh-Wer (Great Knowing)', '𓂋', 'Canonical Kemetic node: Rekh-Wer (Great Knowing).', '[]'::jsonb, 'metaphysical', 36),
('set', 'Set', '𓋴', 'Canonical Kemetic node: Set.', '[]'::jsonb, 'netjer', 37),
('esna_temple', 'Esna Temple', '𓉗', 'Canonical Kemetic node: Esna Temple.', '[]'::jsonb, 'earth', 38),
('shai', 'Šai (Destiny)', '𓋴', 'Canonical Kemetic node: Šai (Destiny).', '["Šai", "Shai", "šai"]'::jsonb, 'netjer', 39),
('offering_formula', 'Offering Formula (ḥtp-dỉ-nsw)', '𓏏', 'Canonical Kemetic node: Offering Formula (ḥtp-dỉ-nsw).', '[]'::jsonb, 'builder', 40),
('shemu', 'Shemu', '𓇓', 'Canonical Kemetic node: Shemu.', '["Season of Completion"]'::jsonb, 'cosmic', 41),
('amduat', 'Amduat', '𓁢', 'Canonical Kemetic node: Amduat.', '[]'::jsonb, 'cosmic', 42),
('khepri', 'Khepri', '𓆣', 'Canonical Kemetic node: Khepri.', '[]'::jsonb, 'netjer', 43),
('hotep', 'ḥtp (Peace/Offering)', '𓊵', 'Canonical Kemetic node: ḥtp (Peace/Offering).', '[]'::jsonb, 'metaphysical', 44),
('instruction_amenemope', 'Instruction of Amenemope', '𓏏', 'Canonical Kemetic node: Instruction of Amenemope.', '[]'::jsonb, 'metaphysical', 45),
('eye_of_ra', 'Eye of Ra', '𓂋', 'Canonical Kemetic node: Eye of Ra.', '[]'::jsonb, 'cosmic', 46),
('tomb_inscriptions', 'Tomb Inscriptions', '𓐍', 'Canonical Kemetic node: Tomb Inscriptions.', '[]'::jsonb, 'metaphysical', 47),
('middle_kingdom_funerary', 'Middle Kingdom Funerary Tradition', '𓊹', 'Canonical Kemetic node: Middle Kingdom Funerary Tradition.', '[]'::jsonb, 'metaphysical', 48),
('nut', 'Nut', '𓇯', 'Canonical Kemetic node: Nut.', '[]'::jsonb, 'cosmic', 49),
('horizon', 'Akhet (Horizon)', '𓈌', 'Canonical Kemetic node: Akhet (Horizon).', '[]'::jsonb, 'cosmic', 50),
('natron', 'Natron', '𓈗', 'Canonical Kemetic node: Natron.', '[]'::jsonb, 'earth', 51),
('nebet_het', 'Nebet-Het', '𓇓', 'Canonical Kemetic node: Nebet-Het.', '["Nebet-Het", "Nephthys"]'::jsonb, 'netjer', 52),
('khnum', 'Khnum', '𓎛𓈖𓅓', 'Canonical Kemetic node: Khnum.', '[]'::jsonb, 'netjer', 53),
('memphite_theology', 'Memphite Theology', '𓉐', 'Canonical Kemetic node: Memphite Theology.', '["Shabaka Stone", "Memphite Theology"]'::jsonb, 'builder', 54),
('book_of_the_dead', 'Book of the Dead', '𓏏', 'Canonical Kemetic node: Book of the Dead.', '["Book of Coming Forth by Day", "Book of the Dead"]'::jsonb, 'metaphysical', 55),
('palermo_stone', 'Palermo Stone', '𓏏𓏤𓏤𓏤 𓂋𓈖𓏏', 'Canonical Kemetic node: Palermo Stone.', '["Royal Annals"]'::jsonb, 'metaphysical', 56),
('wadi_el_jarf_papyri', 'Wadi el-Jarf Papyri (Diary of Merer)', '𓏞 𓂋𓐍𓏤𓂋𓏏 𓏛', 'Canonical Kemetic node: Wadi el-Jarf Papyri (Diary of Merer).', '["Wadi el-Jarf Papyri", "Diary of Merer"]'::jsonb, 'metaphysical', 57),
('false_door', 'False Door', '𓉐𓊹', 'Canonical Kemetic node: False Door.', '[]'::jsonb, 'builder', 58),
('architrave', 'Architrave', '𓉐𓇯', 'Canonical Kemetic node: Architrave.', '[]'::jsonb, 'builder', 59),
('wp_rnpt', 'wp rnpt (Opening of the Year)', '𓅱𓊪 𓂋𓈖𓏏', 'Canonical Kemetic node: wp rnpt (Opening of the Year).', '["wp rnpt", "Opening of the Year", "Wp Rnpt"]'::jsonb, 'cosmic', 60),
('akhet', 'Akhet', '𓇉', 'Canonical Kemetic node: Akhet.', '["Season of Inundation"]'::jsonb, 'cosmic', 61),
('peret', 'Peret', '𓇾', 'Canonical Kemetic node: Peret.', '["Season of Emergence"]'::jsonb, 'cosmic', 62),
('epagomenal_days', 'Epagomenal Days', '𓇋𓏏𓊖 𓏤𓏤𓏤𓏤𓏤', 'Canonical Kemetic node: Epagomenal Days.', '["Five Days Outside the Year"]'::jsonb, 'cosmic', 63),
('regnal_year', 'Regnal Year', '𓂋𓈖𓏏', 'Canonical Kemetic node: Regnal Year.', '["Regnal Count"]'::jsonb, 'metaphysical', 64)
on conflict (slug) do update set
  title = coalesce(nullif(btrim(public.nodes.title), ''), excluded.title),
  glyph = coalesce(
    nullif(btrim(coalesce(public.nodes.glyph, '')), ''),
    excluded.glyph
  ),
  body_text = coalesce(
    nullif(btrim(public.nodes.body_text), ''),
    excluded.body_text
  ),
  aliases = case
    when public.nodes.aliases = '[]'::jsonb then excluded.aliases
    else public.nodes.aliases
  end,
  node_type = coalesce(nullif(btrim(public.nodes.node_type), ''), excluded.node_type),
  sort_key = coalesce(public.nodes.sort_key, excluded.sort_key),
  is_system_owned = true,
  is_active = true,
  updated_at = now();
